/**
 * Message generated by MessengerClient
 */
export interface Message {
  content: string;
  channelId: string;
  username: string;
  date: Date;
  isReplied: boolean;
  replyAuthor: string;
  replyMesage: string;
  isMentioned: boolean;
  isDM: boolean;
}
